language: go

go:
  - 1.6

services:
  - docker

script:
  - export PATH=$PATH:$PWD/bin
  - git clone https://github.com/brimstone/projectbuilder
  - export PROJECTBUILDER=$PWD/projectbuilder
  - make travis
